#define LANG_NAME                        0
#define LANG_ONLY_FOUNDERS               1
#define LANG_EXCEPTS_UNSUPPORTED         2
#define LANG_INVITEMODE_UNSUPPORTED      3
#define LANG_HOPS_UNSUPPORTED            4
#define LANG_CMD_NOT_AV                  5
#define LANG_CMD_DISABLED                6
#define LANG_UNKNOWN_CMD                 7
#define LANG_INVALID_TIME                8
#define LANG_REQ_NICK_OR_MASK            9
#define EXPIRES_S                        10
#define EXPIRES_1S                       11
#define LANG_LEVELS_ERR_NO_VAL           12
#define LANG_LEVELS_ERR_VAL              13
#define LANG_BADWORDS_ERR_STYLE          14
#define LANG_INVITE_NO_USER              15
#define LANG_INVITE_IS_ON                16
#define LANG_INVITE_YOURSELF             17
#define LANG_GOLIST_OPER_ONLY            18
#define LANG_GOLIST_OPER_AND_SO          19
#define LANG_GOLIST_OPER_AND_SA          20
#define LANG_GOLIST_OPER_AND_SRA         21
#define LANG_GOLIST_NONE                 22
#define LANG_GOLIST_HEADER               23
#define LANG_GOLIST_FOOTER               24
#define LANG_ADLIST_SA                   25
#define LANG_ADLIST_SRA                  26
#define LANG_ADLIST_NONE                 27
#define LANG_ADLIST_HEADER               28
#define LANG_ADLIST_FOOTER               29
#define LANG_TBAN_RESPONSE               30
#define LANG_TSHUN_ADDED                 31
#define LANG_TSHUN_DELETION              32
#define LANG_TSHUN_TARGET_NEXIST         33
#define LANG_TSHUN_TARGET_OPER           34
#define LANG_SHUN_ADDED                  35
#define LANG_SHUN_DELETION               36
#define LANG_SUSPEND_NO_REASON           37
#define LANG_SYNC_DONE                   38
#define LANG_UNBAN_NOTE                  39
#define LANG_HELP                        40
#define LANG_CMDLIST                     41
#define LANG_CMD_LIST_HEADER             42
#define LANG_CMD_LIST_FOOTER             43
#define LANG_CMD_LIST_GENERAL            44
#define LANG_CMD_LIST_CHAN_AXX           45
#define LANG_CMD_LIST_CHG_SET            46
#define LANG_CMD_LIST_ACTIONS            47
#define LANG_CMD_LIST_IRCOP              48
#define LANG_CMD_LIST_EXTMODS            49
#define LANG_HELP_UNKNOWN_CMD            50
#define LANG_HELP_CMDS_GEN               51
#define LANG_HELP_CMDS_ACC               52
#define LANG_HELP_CMDS_SETTINGS          53
#define LANG_HELP_CMDS_ACTIONS           54
#define LANG_HELP_CMDS_PUTMODES          55
#define LANG_HELP_CMDS_IRCOP             56
#define LANG_HELP_MORE_INFO              57
#define LANG_HELP_LIST                   58
#define LANG_ACCESS_LEVELS               59
#define LANG_ADMINS_SYNTAX               60
#define LANG_AKICK_SYNTAX                61
#define LANG_AKICK_SYNTAX_EXT            62
#define LANG_AKILL_SYNTAX                63
#define LANG_AKILL_SYNTAX_EXT            64
#define LANG_APPENDT_SYNTAX              65
#define LANG_APPENDT_SYNTAX_EXT          66
#define LANG_BADWORDS_SYNTAX             67
#define LANG_BADWORDS_SYNTAX_EXT         68
#define LANG_BAN_SYNTAX                  69
#define LANG_BAN_SYNTAX_EXT              70
#define LANG_BKICK_SYNTAX                71
#define LANG_BKICK_SYNTAX_EXT            72
#define LANG_BKICK_BOLDS_SYNTAX          73
#define LANG_BKICK_BOLDS_SYNTAX_EXT      74
#define LANG_BKICK_BADWORDS_SYNTAX       75
#define LANG_BKICK_BADWORDS_SYNTAX_EXT   76
#define LANG_BKICK_CAPS_SYNTAX           77
#define LANG_BKICK_CAPS_SYNTAX_EXT       78
#define LANG_BKICK_COLORS_SYNTAX         79
#define LANG_BKICK_COLORS_SYNTAX_EXT     80
#define LANG_BKICK_FLOOD_SYNTAX          81
#define LANG_BKICK_FLOOD_SYNTAX_EXT      82
#define LANG_BKICK_REPEAT_SYNTAX         83
#define LANG_BKICK_REPEAT_SYNTAX_EXT     84
#define LANG_BKICK_REVERSES_SYNTAX       85
#define LANG_BKICK_REVERSES_SYNTAX_EXT   86
#define LANG_BKICK_UNDERLINES_SYNTAX     87
#define LANG_BKICK_UNDERLINES_SYNTAX_EXT 88
#define LANG_BKICK_UNKNOWN_OPTION        89
#define LANG_CLEAR_SYNTAX                90
#define LANG_CLEAR_SYNTAX_EXT            91
#define LANG_CTOPIC_SYNTAX               92
#define LANG_CTOPIC_SYNTAX_EXT           93
#define LANG_DOWN_SYNTAX                 94
#define LANG_DOWN_SYNTAX_EXT             95
#define LANG_IGNORE_SYNTAX               96
#define LANG_IGNORE_SYNTAX_EXT           97
#define LANG_INFO_SYNTAX                 98
#define LANG_INFO_SYNTAX_EXT             99
#define LANG_INVITE_SYNTAX               100
#define LANG_INVITE_SYNTAX_EXT           101
#define LANG_KICKBAN_SYNTAX              102
#define LANG_KICKBAN_SYNTAX_EXT          103
#define LANG_KICK_SYNTAX                 104
#define LANG_KICK_SYNTAX_EXT             105
#define LANG_KILL_SYNTAX                 106
#define LANG_KILL_SYNTAX_EXT             107
#define LANG_MINFO                       108
#define LANG_MUTE_SYNTAX                 109
#define LANG_MUTE_SYNTAX_EXT             110
#define LANG_UNMUTE_SYNTAX               111
#define LANG_UNMUTE_SYNTAX_EXT           112
#define LANG_MODE_SYNTAX                 113
#define LANG_MODE_SYNTAX_EXT             114
#define LANG_PREPENDT_SYNTAX             115
#define LANG_PREPENDT_SYNTAX_EXT         116
#define LANG_RAPPEND_SYNTAX              117
#define LANG_RAPPEND_SYNTAX_EXT          118
#define LANG_RPREPEND_SYNTAX             119
#define LANG_RPREPEND_SYNTAX_EXT         120
#define LANG_SET_SYNTAX                  121
#define LANG_SET_SYNTAX_EXT              122
#define LANG_SET_FOUNDER_SYNTAX          123
#define LANG_SET_FOUNDER_SYNTAX_EXT      124
#define LANG_SET_SUCCESSOR_SYNTAX        125
#define LANG_SET_SUCCESSOR_SYNTAX_EXT    126
#define LANG_SET_DESC_SYNTAX             127
#define LANG_SET_DESC_SYNTAX_EXT         128
#define LANG_SET_URL_SYNTAX              129
#define LANG_SET_URL_SYNTAX_EXT          130
#define LANG_SET_EMAIL_SYNTAX            131
#define LANG_SET_EMAIL_SYNTAX_EXT        132
#define LANG_SET_ENTRYMSG_SYNTAX         133
#define LANG_SET_ENTRYMSG_SYNTAX_EXT     134
#define LANG_SET_BANTYPE_SYNTAX          135
#define LANG_SET_BANTYPE_SYNTAX_EXT      136
#define LANG_SET_MLOCK_SYNTAX            137
#define LANG_SET_MLOCK_SYNTAX_EXT        138
#define LANG_SET_KEEPTOPIC_SYNTAX        139
#define LANG_SET_KEEPTOPIC_SYNTAX_EXT    140
#define LANG_SET_TOPICLOCK_SYNTAX        141
#define LANG_SET_TOPICLOCK_SYNTAX_EXT    142
#define LANG_SET_OPNOTICE_SYNTAX         143
#define LANG_SET_OPNOTICE_SYNTAX_EXT     144
#define LANG_SET_PEACE_SYNTAX            145
#define LANG_SET_PEACE_SYNTAX_EXT        146
#define LANG_SET_PRIVATE_SYNTAX          147
#define LANG_SET_PRIVATE_SYNTAX_EXT      148
#define LANG_SET_RESTRICTED_SYNTAX       149
#define LANG_SET_RESTRICTED_SYNTAX_EXT   150
#define LANG_SET_SECURE_SYNTAX           151
#define LANG_SET_SECURE_SYNTAX_EXT       152
#define LANG_SET_SECUREOPS_SYNTAX        153
#define LANG_SET_SECUREOPS_SYNTAX_EXT    154
#define LANG_SET_SECUREFOUNDER_SYNTAX    155
#define LANG_SET_SECUREFOUNDER_SYNTAX_EXT 156
#define LANG_SET_SIGNKICK_SYNTAX         157
#define LANG_SET_SIGNKICK_SYNTAX_EXT     158
#define LANG_SET_XOP_SYNTAX              159
#define LANG_SET_XOP_SYNTAX_EXT          160
#define LANG_SET_NOEXPIRE_SYNTAX         161
#define LANG_SET_NOEXPIRE_SYNTAX_EXT     162
#define LANG_SET_DONTKICKOPS_SYNTAX      163
#define LANG_SET_DONTKICKOPS_SYNTAX_EXT  164
#define LANG_SET_DONTKICKVOICES_SYNTAX   165
#define LANG_SET_DONTKICKVOICES_SYNTAX_EXT 166
#define LANG_SET_GREET_SYNTAX            167
#define LANG_SET_GREET_SYNTAX_EXT        168
#define LANG_SET_FANTASY_SYNTAX          169
#define LANG_SET_FANTASY_SYNTAX_EXT      170
#define LANG_SET_SYMBIOSIS_SYNTAX        171
#define LANG_SET_SYMBIOSIS_SYNTAX_EXT    172
#define LANG_SET_NOBOT_SYNTAX            173
#define LANG_SET_NOBOT_SYNTAX_EXT        174
#define LANG_SET_UNKNOWN_OPTION          175
#define LANG_SHUN_SYNTAX                 176
#define LANG_SHUN_SYNTAX_EXT             177
#define LANG_STAFF                       178
#define LANG_STATUS_MODE_SYNTAX          179
#define LANG_STATUS_MODE_SYNTAX_EXT      180
#define LANG_SUSPEND_SYNTAX              181
#define LANG_SUSPEND_SYNTAX_EXT          182
#define LANG_SVERSION                    183
#define LANG_SYNC_SYNTAX                 184
#define LANG_SYNC_SYNTAX_EXT             185
#define LANG_TBAN_SYNTAX                 186
#define LANG_TBAN_SYNTAX_EXT             187
#define LANG_TKBAN_SYNTAX                188
#define LANG_TKBAN_SYNTAX_EXT            189
#define LANG_TOPIC_SYNTAX                190
#define LANG_TOPIC_SYNTAX_EXT            191
#define LANG_TSHUN_SYNTAX                192
#define LANG_TSHUN_SYNTAX_EXT            193
#define LANG_UNBAN_SYNTAX                194
#define LANG_UNBAN_SYNTAX_EXT            195
#define LANG_UPDOWN_SYNTAX               196
#define LANG_UP_SYNTAX                   197
#define LANG_UP_SYNTAX_EXT               198
#define LANG_SOP_SYNTAX                  199
#define LANG_SOP_SYNTAX_EXT              200
#define LANG_AOP_SYNTAX                  201
#define LANG_AOP_SYNTAX_EXT              202
#define LANG_HOP_SYNTAX                  203
#define LANG_HOP_SYNTAX_EXT              204
#define LANG_VOP_SYNTAX                  205
#define LANG_VOP_SYNTAX_EXT              206
#define LANG_ACCESS_SYNTAX               207
#define LANG_ACCESS_SYNTAX_EXT           208
#define LANG_LEVELS_SYNTAX               209
#define LANG_LEVELS_SYNTAX_EXT           210

#define MOD_NUM_STRINGS 211
